services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=zonas_quietud' 
      - 'POSTGRES_USER=${DB_USERNAME}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
    ports:
      - '5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    networks:
      - 'zonas_quietud_network'

  redis:
    image: 'redis:latest'
    ports:
      - '6379'
    volumes:
      - 'redis_data:/data'
    networks:
      - 'zonas_quietud_network'

volumes:
  postgres_data:
  redis_data:

networks:
  zonas_quietud_network:
    driver: bridge
