spring:
  application:
    name: zonas-quietud-backend
  datasource:
    url: jdbc:postgresql://{${DB_HOST}}:{${DB_PORT}}/{${DB_NAME}}
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
    driver-class-name: org.postgresql.Driver
  jpa:
    # Este dialecto permite usar funciones como ST_Distance, ST_Within, etc.
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
    hibernate:
      ddl-auto: validate # "validate" es mejor si ya corriste el script SQL manualmente
    properties:
      hibernate:
        format-sql: true # Para ver queries bonitas en consola
